module.exports = {
	Role: require('./Role'),
	BaoVe: require('./BaoVe'),
	SoiThuong: require('./SoiThuong'),
	TienTri: require('./TienTri'),
	PhuThuy: require('./PhuThuy'),
	ThoSan: require('./ThoSan'),
	DanLang: require('./DanLang'),
	Minion: require('./Minion'),
	SoiTienTri: require('./SoiTienTri'),
	PhapSuCam: require('./PhapSuCam'),
	ChanDoi: require('./ChanDoi'),
	ThayDong: require('./ThayDong'),
	Vampire: require('./Vampire'),
	BanSoi: require('./BanSoi'),
	Waller: require('./Waller'),
	GiaLang: require('./GiaLang'),
	Lycan: require('./Lycan'),
	NhanBan: require('./NhanBan'),
	Harlot: require('./Harlot'),
	Alchemist: require('./Alchemist'),
	SoiBongDem: require('./SoiBongDem'),
	SoiDeThuong: require('./SoiDeThuong'),
	KySi: require('./KySi'),
	ConDo: require('./ConDo'),
	VongHon: require('./VongHon'),
	NhaNgoaiCam: require('./NhaNgoaiCam'),
	SoiKySinh: require('./SoiKySinh')
	
};
